# Generated by Django 4.2.4 on 2023-09-15 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0011_members_mobile_number_first'),
        ('monitor', '0014_remove_memberproblems_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Problem Solved')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.members', verbose_name='Member')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='monitor.monitorrules', verbose_name='Problem')),
            ],
            options={
                'verbose_name': 'Member Problem',
                'verbose_name_plural': 'Member Problems',
                'db_table': 'member_problem',
            },
            managers=[
                ('unsolved', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_progress', models.TextField(default=None, null=True, verbose_name='Update Progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_problems', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_problems', to='problems.memberproblems')),
            ],
            options={
                'db_table': 'problem_update',
            },
        ),
        migrations.CreateModel(
            name='MemberProblemsDone',
            fields=[
            ],
            options={
                'verbose_name': 'Problem History',
                'verbose_name_plural': 'Problems History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('problems.memberproblems',),
        ),
    ]
