# Generated by Django 4.2.4 on 2023-10-30 03:29

from django.db import migrations, models
import django.db.models.deletion
import webfilters.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_members_mobile_number_first'),
        ('networks', '0001_initial'),
        ('accounts', '0015_features_is_webfilter_multinet'),
        ('webfilters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfilters',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.networks', verbose_name='Network'),
        ),
        migrations.CreateModel(
            name='WebFiltersOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networks.networks', verbose_name='Network')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='accounts.organizations', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Web Filter Network ',
                'verbose_name_plural': 'Web Filters Network ',
                'db_table': 'webfilter_org',
            },
        ),
        migrations.CreateModel(
            name='WebFiltersMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(limit_choices_to=webfilters.models.WebFiltersMembers.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='members.members', verbose_name='Member')),
                ('webfilter', models.ForeignKey(limit_choices_to=webfilters.models.WebFiltersMembers.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='webfilters.webfilters', verbose_name='WebFilter')),
            ],
            options={
                'verbose_name': 'WebFilter Member',
                'verbose_name_plural': 'WebFilter Members',
                'db_table': 'webfilter_member',
            },
        ),
    ]
