# Generated by Django 4.2.4 on 2023-10-30 05:10

from django.db import migrations, models
import django.db.models.deletion
import webfilters.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_members_is_waf'),
        ('webfilters', '0002_webfilters_network_webfiltersorg_webfiltersmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webfiltersmembers',
            name='member',
            field=models.OneToOneField(limit_choices_to=webfilters.models.WebFiltersMembers.limit_choices_to_member, on_delete=django.db.models.deletion.CASCADE, to='members.members', verbose_name='Member'),
        ),
    ]
