# Generated by Django 4.2.4 on 2023-12-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfilters', '0004_webfilters_domains_white_webfilters_is_default_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webfilters',
            name='domains',
            field=models.TextField(default='atleastonedomain.com', help_text='List top domain to block', verbose_name='Black List'),
        ),
        migrations.AlterField(
            model_name='webfilters',
            name='is_default_block',
            field=models.BooleanField(default=False, help_text='Check this for block all website as default', verbose_name='Default Block All'),
        ),
    ]
