# Generated by Django 4.2.4 on 2023-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfilters', '0006_alter_webfilters_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webfilters',
            name='domains_white',
            field=models.TextField(default='atleastonedomain.com', help_text='List top domain to allow', verbose_name='White List'),
        ),
    ]
