# Generated by Django 4.2.4 on 2024-01-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_members_is_waf'),
        ('webfilters', '0008_alter_webfilters_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFiltersMembersList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.members',),
        ),
    ]
