# Generated by Django 4.0.6 on 2022-12-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='ssh',
            field=models.BooleanField(default=False, verbose_name='Remote SSH Feature'),
        ),
        migrations.AddField(
            model_name='features',
            name='web',
            field=models.BooleanField(default=False, verbose_name='Remote Web Feature'),
        ),
    ]
