# Generated by Django 4.0.6 on 2022-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_features_authorize_alter_features_bridge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='synchronize',
            field=models.BooleanField(default=False, verbose_name='Synchronize'),
        ),
    ]
