# Generated by Django 4.1 on 2023-08-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_features_synchronize'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='geolocation',
            field=models.BooleanField(default=False, verbose_name='GeoLocation'),
        ),
        migrations.AddField(
            model_name='features',
            name='online_offline',
            field=models.BooleanField(default=False, verbose_name='Online/Offline'),
        ),
    ]
