# Generated by Django 4.1 on 2023-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_features_geolocation_features_online_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_telkomsel',
            field=models.BooleanField(default=False, verbose_name='Telkomsel Project'),
        ),
    ]
