# Generated by Django 4.1 on 2023-08-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_features_is_telkomsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_export',
            field=models.BooleanField(default=False, verbose_name='Export Data'),
        ),
    ]
