# Generated by Django 4.1 on 2023-08-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_features_is_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='mobile_connect',
            field=models.BooleanField(default=False, verbose_name='Mobile Connect'),
        ),
    ]
