# Generated by Django 4.2.4 on 2023-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_features_mobile_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='map_dashboard',
            field=models.BooleanField(default=False, verbose_name='Map Dashboard'),
        ),
    ]
