# Generated by Django 4.2.4 on 2023-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_features_number_of_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='number_of_member',
            field=models.IntegerField(default=10, verbose_name='Number of Members'),
        ),
    ]
