# Generated by Django 4.2.4 on 2023-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_features_number_of_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_simple_list',
            field=models.BooleanField(default=False, verbose_name='Simple List'),
        ),
    ]
