# Generated by Django 4.2.4 on 2023-10-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_features_is_simple_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_webfilter',
            field=models.BooleanField(default=False, verbose_name='Web Filters'),
        ),
    ]
