# Generated by Django 4.2.4 on 2023-10-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_features_is_webfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_webfilter_multinet',
            field=models.BooleanField(default=False, verbose_name='Web Filters Multi Net'),
        ),
    ]
