# Generated by Django 4.2.4 on 2023-12-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_features_is_webfilter_multinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_lte_signal',
            field=models.BooleanField(default=False, verbose_name='LTE Signal'),
        ),
    ]
