# Generated by Django 4.2.11 on 2024-03-07 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_features_is_lte_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d825510-e470-46a3-b7d9-b73dfcf60303'), editable=False, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a8687062-aaef-4c8a-863b-67fd36083d34'), editable=False, verbose_name='UUID'),
        ),
    ]
