# Generated by Django 4.2.11 on 2024-03-07 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_features_uuid_organizations_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0a15f327-05f1-49a1-8d15-5bf2bdbef84f'), editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3ec09730-cac6-4f3c-9c1e-38ae90f5cfac'), editable=False, verbose_name='UUID'),
        ),
    ]
