# Generated by Django 4.2.11 on 2024-03-12 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_features_uuid_alter_organizations_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7edd6f25-3e67-469e-80c6-2ff122817f67'), editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('23bdce4d-f79b-48ca-97b2-2386f59fc41e'), editable=False, verbose_name='UUID'),
        ),
    ]
