# Generated by Django 4.2.11 on 2024-03-12 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_features_uuid_alter_organizations_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('38e2ce93-63aa-4141-8ade-739d1497a9c9'), editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e0ea6b83-c277-4c5e-a433-19e1a748de90'), editable=False, verbose_name='UUID'),
        ),
    ]
