# Generated by Django 4.2.11 on 2024-03-12 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_features_uuid_remove_organizations_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('83bcbbfb-32a2-4905-b2ff-290d46cbb38d'), editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca618719-9f4f-49de-a032-048e2f242227'), editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
