# Generated by Django 4.2.11 on 2024-03-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_features_uuid_organizations_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='uuid',
        ),
    ]
