# Generated by Django 4.2.11 on 2024-03-12 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_features_uuid_remove_organizations_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
    ]
