# Generated by Django 4.2.11 on 2024-03-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20240312_1413'),
    ]

    operations = [
    ]
