# Generated by Django 4.2.11 on 2024-10-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_features_uuid_alter_organizations_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_dpi',
            field=models.BooleanField(default=False, verbose_name='DPI'),
        ),
    ]
