# Generated by Django 4.2.11 on 2025-02-21 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('accounts', '0030_features_is_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to='wagtailimages.image', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Brand logo used in the navbar and throughout the site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
