# Generated by Django 4.2.19 on 2025-02-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('accounts', '0031_organizations_favicon_organizations_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='logo_dashboard',
            field=models.ForeignKey(blank=True, help_text='Brand logo used in dashboard (512x512 pixels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Dashboard'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Brand logo used in login or throughout the site (512x128 pixels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
    ]
