# Generated by Django 4.2.19 on 2025-02-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('accounts', '0032_organizations_logo_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Favicon file with extension .ico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to='wagtailimages.image', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
