# Generated by Django 4.2.19 on 2025-02-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('accounts', '0033_alter_organizations_favicon_alter_organizations_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='site',
            field=models.OneToOneField(blank=True, help_text='If this organization refer to same site with other organization, leave it empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
