# Generated by Django 4.2.19 on 2025-06-16 06:36

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_grouporganizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporganizations',
            name='main_org',
            field=models.ForeignKey(limit_choices_to=accounts.models.GroupOrganizations.limit_choice_no_org, on_delete=django.db.models.deletion.CASCADE, to='accounts.organizations', verbose_name='Main Organization'),
        ),
        migrations.AlterField(
            model_name='grouporganizations',
            name='member_org',
            field=modelcluster.fields.ParentalManyToManyField(limit_choices_to=accounts.models.GroupOrganizations.limit_choice_no_org, related_name='member_org', to='accounts.organizations'),
        ),
    ]
