# Generated by Django 4.2.19 on 2025-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_grouporganizations_main_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_deauth_timer',
            field=models.BooleanField(default=False, verbose_name='De-Authorize Timer'),
        ),
    ]
