# Generated by Django 4.2.19 on 2025-09-02 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_features_is_deauth_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('number_of_network', models.IntegerField(default=1, verbose_name='Number of Networks')),
                ('network_multi_ip', models.BooleanField(default=False, verbose_name='Network Multi IP')),
                ('network_rules', models.BooleanField(default=False, verbose_name='Network Rules')),
                ('number_of_member', models.IntegerField(default=10, verbose_name='Number of Members')),
                ('member_multi_ip', models.BooleanField(default=False, verbose_name='Member Multi IP')),
                ('authorize', models.BooleanField(default=False, verbose_name='Authorize')),
                ('bridge', models.BooleanField(default=False, verbose_name='Bridge')),
                ('tags', models.BooleanField(default=False, verbose_name='Tags')),
                ('web', models.BooleanField(default=False, verbose_name='Remote Web')),
                ('ssh', models.BooleanField(default=False, verbose_name='Remote SSH')),
                ('synchronize', models.BooleanField(default=False, verbose_name='Synchronize')),
                ('geolocation', models.BooleanField(default=False, verbose_name='GeoLocation')),
                ('online_offline', models.BooleanField(default=False, verbose_name='Online/Offline')),
                ('is_export', models.BooleanField(default=False, verbose_name='Export Data')),
                ('mobile_connect', models.BooleanField(default=False, verbose_name='Mobile Connect')),
                ('map_dashboard', models.BooleanField(default=False, verbose_name='Map Dashboard')),
                ('is_nms', models.BooleanField(default=False, verbose_name='Monitoring')),
                ('is_webfilter', models.BooleanField(default=False, verbose_name='Web Filters')),
                ('is_webfilter_multinet', models.BooleanField(default=False, verbose_name='Web Filters Multi Net')),
                ('is_dpi', models.BooleanField(default=False, verbose_name='DPI')),
                ('is_telkomsel', models.BooleanField(default=False, verbose_name='Telkomsel Project')),
                ('is_deauth_timer', models.BooleanField(default=False, verbose_name='De-Authorize Timer')),
                ('is_simple_list', models.BooleanField(default=False, verbose_name='Simple List')),
                ('is_lte_signal', models.BooleanField(default=False, verbose_name='LTE Signal')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License Feature',
                'verbose_name_plural': 'License Features',
                'db_table': 'license_features',
            },
        ),
    ]
