# Generated by Django 4.2.19 on 2025-09-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_licensefeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='license_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.licensefeatures', verbose_name='Features'),
        ),
    ]
