# Generated by Django 4.2.19 on 2025-09-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_alter_licenses_license_features'),
        ('accounts', '0039_organizations_license_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='license_features',
        ),
        migrations.DeleteModel(
            name='LicenseFeatures',
        ),
    ]
