# Generated by Django 4.2.19 on 2025-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_organizations_license_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
