# Generated by Django 5.2.8 on 2026-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_member_filter',
            field=models.BooleanField(default=False, verbose_name='Member Filter'),
        ),
    ]
