# Generated by Django 5.2.12 on 2026-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_user_is_member_filter'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='site',
        ),
        migrations.AddField(
            model_name='organizations',
            name='site',
            field=models.ManyToManyField(blank=True, help_text='If this organization refer to same site with other organization, leave it empty.', null=True, to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
