# Generated by Django 5.2.12 on 2026-04-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organizations_site_organizations_site'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='site',
            field=models.ManyToManyField(blank=True, help_text='If this organization refer to same site with other organization, leave it empty.', null=True, related_name='site_organization', to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
