# Generated by Django 5.2.12 on 2026-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_organizations_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_remote_ssh',
            field=models.BooleanField(default=False, verbose_name='Remote SSH'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_remote_web',
            field=models.BooleanField(default=False, verbose_name='Remote WEB'),
        ),
    ]
