# Generated by Django 5.2.12 on 2026-04-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_user_is_remote_ssh_user_is_remote_web'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='site',
            field=models.ManyToManyField(blank=True, help_text='If this organization refer to same site with other organization, leave it empty.', related_name='site_organization', to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
