# Generated by Django 4.0.6 on 2022-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='is_rcall',
            field=models.BooleanField(default=False, verbose_name='RCALL Running'),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='uptime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uptime'),
        ),
    ]
