# Generated by Django 4.0.6 on 2023-01-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_mqtt_is_rcall_mqtt_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SN'),
        ),
    ]
