# Generated by Django 4.0.6 on 2023-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_mqtt_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='memory_usage',
            field=models.FloatField(default=0.0, verbose_name='Memory Usage'),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='num_core',
            field=models.IntegerField(default=1, verbose_name='Number of Core'),
        ),
    ]
