# Generated by Django 4.0.6 on 2023-01-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_mqtt_memory_usage_mqtt_num_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='cpu_usage',
            field=models.FloatField(default=0.0, verbose_name='CPU Usage'),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='packet_loss',
            field=models.FloatField(default=0, verbose_name='Packet Lost'),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='packet_loss_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packet Loss String'),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='round_trip',
            field=models.FloatField(default=0, verbose_name='Round Trip'),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='round_trip_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Round Trip String'),
        ),
    ]
