# Generated by Django 4.1 on 2023-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_mqtt_cpu_usage_mqtt_packet_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='switchport_up',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Switch Port Up'),
        ),
    ]
