# Generated by Django 4.1 on 2023-08-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_mqtt_switchport_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='port_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Port Status'),
        ),
    ]
