# Generated by Django 4.1 on 2023-08-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0007_mqtt_port_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='port_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Port Status'),
        ),
    ]
