# Generated by Django 4.1 on 2023-08-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0008_alter_mqtt_port_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='quota_first',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quota'),
        ),
    ]
