# Generated by Django 4.2.4 on 2023-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0011_mqtt_ipaddress_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='quota_first_prev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quota Prev Day'),
        ),
    ]
