# Generated by Django 4.2.4 on 2023-12-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0013_mqtt_is_waf'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='rssi_signal',
            field=models.IntegerField(default=0, verbose_name='RSSI Signal'),
        ),
    ]
