# Generated by Django 4.2.11 on 2024-11-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0015_mqtt_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='netify_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Netify UUID'),
        ),
    ]
