# Generated by Django 4.2.19 on 2025-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0016_mqtt_netify_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttRedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True, verbose_name='Member ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MQTT Redis',
                'verbose_name_plural': 'MQTT Redis',
                'db_table': 'mqtt_redis',
            },
        ),
    ]
