# Generated by Django 4.2.19 on 2025-06-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0017_mqttredis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
