# Generated by Django 4.2.19 on 2025-06-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0018_mqtt_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MqttRedis',
        ),
    ]
