# Generated by Django 4.0.6 on 2022-08-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controllers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Controller', max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uri', models.URLField(default='http://localhost:9993', max_length=100, unique=True, verbose_name='URL')),
                ('token', models.CharField(max_length=50, unique=True, verbose_name='Token')),
                ('configuration', models.TextField(blank=True, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'controller',
                'verbose_name_plural': 'controllers',
                'db_table': 'controllers',
            },
        ),
        migrations.CreateModel(
            name='UserControllers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.controllers', verbose_name='Controller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user Controller',
                'verbose_name_plural': 'user Controllers',
                'db_table': 'user_controller',
            },
        ),
    ]
