# Generated by Django 4.0.6 on 2022-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controllers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Controller', max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uri', models.URLField(default='http://localhost:9993', max_length=100, unique=True, verbose_name='URL')),
                ('token', models.CharField(max_length=50, unique=True, verbose_name='Token')),
                ('configuration', models.TextField(blank=True, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'controller',
                'verbose_name_plural': 'controllers',
                'db_table': 'controllers',
            },
        ),
    ]
