# Generated by Django 4.0.6 on 2022-08-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllers',
            name='node_id',
        ),
        migrations.AlterField(
            model_name='controllers',
            name='name',
            field=models.CharField(default='Default Controller', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='controllers',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='Token'),
        ),
    ]
