# Generated by Django 4.2.19 on 2025-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_alter_controllers_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllers',
            name='uri',
            field=models.URLField(default='http://localhost:9993', max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
