# Generated by Django 4.0.6 on 2023-01-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_members_serialnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Item')),
                ('item_id', models.CharField(max_length=50, unique=True, verbose_name='Item Keyword')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor Item',
                'verbose_name_plural': 'Monitor Items',
                'db_table': 'monitor_items',
            },
        ),
        migrations.CreateModel(
            name='MonitorRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Problem Name')),
                ('item_threshold', models.FloatField(default=0, help_text='Float Value', verbose_name='Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitoritems', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Monitor Rule',
                'verbose_name_plural': 'Monitor Rules',
                'db_table': 'monitor_rules',
            },
        ),
        migrations.CreateModel(
            name='MemberProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Problem Solved')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.members', verbose_name='Member')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='monitor.monitorrules', verbose_name='Problem')),
            ],
            options={
                'verbose_name': 'Member Problem',
                'verbose_name_plural': 'Member Problems',
                'db_table': 'member_problem',
            },
        ),
    ]
