# Generated by Django 4.0.6 on 2023-01-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_mqtt_memory_usage_mqtt_num_core'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberproblems',
            name='mqtt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mqtt.mqtt', verbose_name='Mqtt'),
        ),
    ]
