# Generated by Django 4.0.6 on 2023-01-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_features_synchronize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0003_monitorrules_organization_monitorrules_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberproblems',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizations', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='memberproblems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
