# Generated by Django 4.0.6 on 2023-01-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_memberproblemsdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberproblems',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
    ]
