# Generated by Django 4.2.4 on 2023-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_problemupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemupdate',
            name='update_progress',
            field=models.TextField(blank=True, null=True, verbose_name='Update Progress'),
        ),
    ]
