# Generated by Django 4.2.4 on 2023-09-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_problemupdate_update_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemupdate',
            name='update_progress',
            field=models.TextField(default=None, null=True, verbose_name='Update Progress'),
        ),
    ]
