# Generated by Django 4.2.4 on 2023-09-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alter_problemupdate_update_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberproblemsdone',
            options={'verbose_name': 'Problem History', 'verbose_name_plural': 'Problems History'},
        ),
    ]
