# Generated by Django 4.2.4 on 2023-09-14 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
        ('accounts', '0009_features_map_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0012_alter_memberproblemsdone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mon', models.BooleanField(default=True, verbose_name='Monday')),
                ('mon_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('mon_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('is_tue', models.BooleanField(default=True, verbose_name='Tuesday')),
                ('tue_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('tue_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('is_wed', models.BooleanField(default=True, verbose_name='Wednesday')),
                ('wed_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('wed_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('is_thu', models.BooleanField(default=True, verbose_name='Thursday')),
                ('thu_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('thu_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('is_fri', models.BooleanField(default=True, verbose_name='Friday')),
                ('fri_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('fri_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('is_sat', models.BooleanField(default=False, verbose_name='Saturday')),
                ('sat_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('sat_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('is_sun', models.BooleanField(default=False, verbose_name='Sunday')),
                ('sun_start', models.IntegerField(default=7, validators=[monitor.models.validate_time], verbose_name='Start')),
                ('sun_end', models.IntegerField(default=17, validators=[monitor.models.validate_time], verbose_name='End')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(limit_choices_to=monitor.models.OperationalTime.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizations', verbose_name='Organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Operational Time',
                'verbose_name_plural': 'Operational Time',
                'db_table': 'operational_time',
            },
        ),
    ]
