# Generated by Django 4.2.4 on 2023-09-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_operationaltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberproblems',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberproblems',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemupdate',
            name='member_problems',
        ),
        migrations.DeleteModel(
            name='MemberProblemsDone',
        ),
        migrations.DeleteModel(
            name='MemberProblems',
        ),
        migrations.DeleteModel(
            name='ProblemUpdate',
        ),
    ]
