# Generated by Django 4.2.11 on 2024-08-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0002_networkrules_is_block_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('networks', models.ManyToManyField(to='networks.networks')),
            ],
            options={
                'verbose_name': 'Zabbix Network',
                'verbose_name_plural': 'Zabbix Networks',
                'db_table': 'zabbix_networks',
            },
        ),
    ]
