# Generated by Django 4.2.11 on 2024-08-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixnetworks',
            name='name',
            field=models.CharField(default='ZabbixNet', max_length=50, verbose_name='Name'),
        ),
    ]
