# Generated by Django 4.0.6 on 2022-08-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import networks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('network_id', models.CharField(max_length=50, unique=True, verbose_name='Network ID')),
                ('ip_address_networks', models.CharField(blank=True, help_text='Example: 192.168.0.0/24, 10.0.0.0/24', max_length=100, null=True, verbose_name='IP Networks')),
                ('configuration', models.TextField(blank=True, verbose_name='Configuration')),
                ('route', models.TextField(blank=True, verbose_name='Route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.controllers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='NetworkRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(blank=True, verbose_name='Network Rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.OneToOneField(limit_choices_to=networks.models.NetworkRules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'network rule',
                'verbose_name_plural': 'network rules',
                'db_table': 'network_rules',
            },
        ),
        migrations.CreateModel(
            name='NetworkRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_network', models.CharField(help_text='Example: 192.168.0.0/24', max_length=50, verbose_name='IP Network')),
                ('gateway', models.GenericIPAddressField(null=True, verbose_name='Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(limit_choices_to=networks.models.NetworkRoutes.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'network route',
                'verbose_name_plural': 'network routes',
                'db_table': 'network_routes',
            },
        ),
    ]
