# Generated by Django 4.0.6 on 2022-08-11 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import networks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPeers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peers', models.TextField(verbose_name='Peers')),
                ('member_id', models.CharField(max_length=50, verbose_name='Member ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.controllers', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'member peer',
                'verbose_name_plural': 'member peers',
                'db_table': 'member_peers',
            },
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('network_id', models.CharField(max_length=50, unique=True, verbose_name='Network ID')),
                ('ip_assignment', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Assignment')),
                ('ip_assignment_netmask', models.IntegerField(choices=[(24, '24'), (23, '23'), (22, '22'), (21, '21'), (20, '20'), (19, '19'), (18, '18'), (17, '17'), (16, '16'), (15, '15'), (14, '14'), (13, '13'), (12, '12'), (11, '11'), (10, '10'), (9, '9'), (8, '8')], default=24, verbose_name='IP Netmask')),
                ('configuration', models.TextField(blank=True, verbose_name='Configuration')),
                ('route', models.TextField(blank=True, verbose_name='Route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.controllers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='NetworkRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(blank=True, verbose_name='Network Rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.OneToOneField(limit_choices_to=networks.models.NetworkRules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'network rule',
                'verbose_name_plural': 'network rules',
                'db_table': 'network_rules',
            },
        ),
        migrations.CreateModel(
            name='NetworkRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_network', models.GenericIPAddressField(verbose_name='IP Network')),
                ('ip_netmask', models.IntegerField(choices=[(24, '24'), (23, '23'), (22, '22'), (21, '21'), (20, '20'), (19, '19'), (18, '18'), (17, '17'), (16, '16'), (15, '15'), (14, '14'), (13, '13'), (12, '12'), (11, '11'), (10, '10'), (9, '9'), (8, '8')], default=24, verbose_name='Netmask')),
                ('gateway', models.GenericIPAddressField(null=True, verbose_name='Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(limit_choices_to=networks.models.NetworkRoutes.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'network route',
                'verbose_name_plural': 'network routes',
                'db_table': 'network_routes',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Member Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('member_id', models.CharField(max_length=50, verbose_name='Member ID')),
                ('is_authorized', models.BooleanField(default=True, verbose_name='Authorized')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('configuration', models.TextField(blank=True, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(limit_choices_to=networks.models.Members.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
                ('peers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.memberpeers', verbose_name='Peers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'db_table': 'members',
            },
        ),
    ]
