# Generated by Django 4.0.6 on 2022-08-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='version',
        ),
    ]
