# Generated by Django 4.2.11 on 2024-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkrules',
            name='is_block_rule',
            field=models.BooleanField(default=False, verbose_name='Block Traffic'),
        ),
    ]
