# Generated by Django 4.2.11 on 2024-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Node ID')),
                ('license_key', models.TextField(blank=True, null=True, verbose_name='License Key')),
                ('license_string', models.TextField(blank=True, null=True, verbose_name='License String')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licences',
            },
        ),
    ]
