# Generated by Django 4.2.11 on 2024-03-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_features_uuid_alter_organizations_uuid'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenses',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizations', verbose_name='Organization'),
        ),
    ]
