# Generated by Django 4.2.11 on 2024-03-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_licenses_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='license_string',
            field=models.TextField(blank=True, null=True, verbose_name='License Code'),
        ),
    ]
