# Generated by Django 4.2.11 on 2024-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_alter_licenses_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenses',
            name='is_block_rule',
            field=models.BooleanField(default=True, verbose_name='Block Rule at Expired'),
        ),
    ]
