# Generated by Django 4.2.19 on 2025-09-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_organizations_license_features'),
        ('licenses', '0007_licenses_license_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='license_features',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.licensefeatures', verbose_name='LicenseFeatures'),
        ),
    ]
