# Generated by Django 4.2.19 on 2025-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_licenses_license_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='license_features',
            field=models.TextField(blank=True, default='{}', editable=False, verbose_name='License Features'),
        ),
    ]
