# Generated by Django 4.0.6 on 2023-01-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_mqtt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='serialnumber',
        ),
    ]
