# Generated by Django 4.0.6 on 2023-01-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_members_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
