# Generated by Django 4.0.6 on 2023-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_members_address_members_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='online_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Online'),
        ),
    ]
