# Generated by Django 4.0.6 on 2023-02-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_members_online_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='online_at',
            field=models.DateField(blank=True, null=True, verbose_name='Start Online'),
        ),
    ]
