# Generated by Django 4.1 on 2023-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_members_online_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='offline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stop Online'),
        ),
    ]
