# Generated by Django 4.1 on 2023-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_members_offline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Member Code'),
        ),
    ]
