# Generated by Django 4.1 on 2023-08-29 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_members_member_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mobile_number_first',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '628XXXXXXXXXXX'. Up to 15 digits allowed.", regex='^62\\d{9,15}$')], verbose_name='Mobile Number'),
        ),
    ]
