# Generated by Django 4.2.4 on 2023-10-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_members_mobile_number_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_waf',
            field=models.BooleanField(default=False, verbose_name='WebFilter Active'),
        ),
    ]
