# Generated by Django 4.2.11 on 2024-10-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_members_mobile_number_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_dpi',
            field=models.BooleanField(default=False, verbose_name='DPI'),
        ),
    ]
