# Generated by Django 4.2.19 on 2025-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_members_is_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='quota_first_prev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quota Prev Day'),
        ),
    ]
