# Generated by Django 4.2.19 on 2025-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_members_quota_first_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='quota_first',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quota'),
        ),
    ]
