# Generated by Django 4.2.19 on 2025-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_members_quota_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='deauth_timer',
            field=models.IntegerField(default=0, help_text='In Hour', verbose_name='De-Authorize Timer'),
        ),
        migrations.AddField(
            model_name='members',
            name='deauth_timer_start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='De-Authorize Timer Start'),
        ),
    ]
