# Generated by Django 4.2.19 on 2025-08-25 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_members_deauth_timer_members_deauth_timer_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='deauth_timer_start',
        ),
        migrations.AlterField(
            model_name='members',
            name='deauth_timer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='De-Authorize Timer (Hour)'),
        ),
    ]
