# Generated by Django 4.2.19 on 2025-08-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_remove_members_deauth_timer_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='deauth_timer_start',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='De-Authorize Timer Start'),
        ),
    ]
