# Generated by Django 5.2.12 on 2026-04-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_members_deauth_timer_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_backone_online',
            field=models.BooleanField(default=False, verbose_name='BackOne Status'),
        ),
    ]
